[package]
name = "ferris_space_defender"
version = "0.1.0"
edition = "2021"

[package.metadata.android]
package = "com.ferriskey.spacedefender"
label = "Ferris Defender"
target_sdk_version = 34
min_sdk_version = 24

[package.metadata.android.signing.release]
path = "/home/alek/.android/debug.keystore"
keystore_password = "android"
key_alias = "androiddebugkey"
key_password = "android"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
rand = "0.8"

[target.'cfg(not(target_os = "android"))'.dependencies]
eframe = { version = "0.31", features = ["default_fonts", "glow", "x11", "wayland"] }

[target.'cfg(target_os = "android")'.dependencies]
android-activity = { version = "0.6", features = ["native-activity"] }
eframe = { version = "0.31", default-features = false, features = ["default_fonts", "glow", "android-native-activity"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
